stages:
  - build
  - deploy

build:prod:
  image: node:22.18
  stage: build
  script:
    - npm ci
    - npm run build
    - mv dist dist_prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist_prod
  only:
    - main

deploy:prod:
  image: alpine
  stage: deploy
  environment:
    name: prod
    url: https://jennie.gigabit.dev/
  only:
    - main
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PW $FTP_HOST; mirror -Rnev dist_prod/ /httpdocs --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
